### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by romaincointepas** [elazarl/goproxy#154]
In case this helps, this happens when I'm *refreshing the same https URL like crazy*.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4633f6]

goroutine 69 [running]:
panic(0x771260, 0xc82000a130)
	/usr/lib/go/src/runtime/panic.go:464 +0x3e6
log.(*Logger).Output(0x0, 0x2, 0xc8204d2370, 0xad, 0x0, 0x0)
	/usr/lib/go/src/log/log.go:147 +0x4e6
log.(*Logger).Printf(0x0, 0xc8202a1890, 0x29, 0xc82036ba20, 0x2, 0x2)
	/usr/lib/go/src/log/log.go:173 +0x7e
github.com/elazarl/goproxy.(*ProxyCtx).printf(0xc8203a8eb0, 0xc8202a1860, 0x21, 0xc820049f38, 0x1, 0x1)
	/go/src/github.com/elazarl/goproxy/ctx.go:44 +0x2dd
github.com/elazarl/goproxy.(*ProxyCtx).Warnf(0xc8203a8eb0, 0x82eb80, 0x1b, 0xc820049f38, 0x1, 0x1)
	/go/src/github.com/elazarl/goproxy/ctx.go:73 +0x98
github.com/elazarl/goproxy.copyAndClose(0xc8203a8eb0, 0x7f27056d5a08, 0xc8205188f8, 0x7f27056d5a08, 0xc820518990)
	/go/src/github.com/elazarl/goproxy/https.go:260 +0x1c5
created by github.com/elazarl/goproxy.(*ProxyHttpServer).handleHttps
	/go/src/github.com/elazarl/goproxy/https.go:101 +0xaa4
```

**Comment by ErikPelli** [comment]
Is this issue still present? Someone else found it?
Looks like a logging problem
