### ISSUE TITLE
Default embedded certificate cannot be parsed with Go ~ 1.8 (tip)

### ISSUE THREAD

**Issue by pmezard** [elazarl/goproxy#188]
Hello, 

Since this Go commit:

  crypto/x509: require a NULL parameters for RSA public keys. 
  https://github.com/golang/go/commit/59aeac20c0412442848982a9287b4bab66c25682

The certificate in certs.go fails to parse with:

  panic: Error parsing builtin CA x509: RSA key missing NULL parameters

Maybe it is time to generate a new one.

**Comment by shaicoleman** [comment]
If a new certificate is generated to fix this issue, please ensure that it has all the valid fields so that it can be also be trusted by OS. The current certificate can't be trusted by the OS (tested on Ubuntu 16.04),
http://askubuntu.com/questions/73287/how-do-i-install-a-root-certificate/94861#94861
http://docs.mitmproxy.org/en/stable/certinstall.html#certinstall

**Comment by shaicoleman** [comment]
Go 1.8 released now

**Comment by mikkeloscar** [comment]
I hit this error running tests from kubernetes:

```
KUBERNETES_CONFORMANCE_TEST=Y \                                                                                                     [0]
  KUBERNETES_PROVIDER=skeleton \
  KUBECTL_PATH=$(which kubectl) \
  kubetest -test -check_version_skew=false -v \
  --test_args="--ginkgo.focus=\[Conformance\]"
2017/02/20 15:17:58 util.go:96: Running: ./cluster/kubectl.sh version --match-server-version=false
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2+coreos.0", GitCommit:"3ed7d0f453a5517245d32a9c57c39b946e578821", GitTreeState:"clean", BuildDate:"2017-01-13T00:23:19Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
2017/02/20 15:17:59 util.go:98: Step './cluster/kubectl.sh version --match-server-version=false' finished in 709.827472ms
2017/02/20 15:17:59 util.go:96: Running: ./hack/e2e-internal/e2e-status.sh
Skeleton Provider: prepare-e2e not implemented
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2+coreos.0", GitCommit:"3ed7d0f453a5517245d32a9c57c39b946e578821", GitTreeState:"clean", BuildDate:"2017-01-13T00:23:19Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
2017/02/20 15:17:59 util.go:98: Step './hack/e2e-internal/e2e-status.sh' finished in 501.190718ms
2017/02/20 15:17:59 util.go:96: Running: ./hack/ginkgo-e2e.sh --ginkgo.focus=\[Conformance\]
Conformance test: not doing test setup.
panic: Error parsing builtin CA x509: RSA key missing NULL parameters

goroutine 1 [running]:
k8s.io/kubernetes/vendor/github.com/elazarl/goproxy.init.1()
	/home/moscar/projects/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/elazarl/goproxy/certs.go:10 +0x1e3
k8s.io/kubernetes/vendor/github.com/elazarl/goproxy.init()
	/home/moscar/projects/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/elazarl/goproxy/signer.go:88 +0x2eb
k8s.io/kubernetes/test/e2e.init()
	/home/moscar/projects/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/taints_test.go:336 +0x230
main.init()
	k8s.io/kubernetes/test/e2e/_test/_testmain.go:46 +0x53

Ginkgo ran 1 suite in 110.74848ms
Test Suite Failed
!!! Error in ./hack/ginkgo-e2e.sh:117
  Error in ./hack/ginkgo-e2e.sh:117. '"${ginkgo}" "${ginkgo_args[@]:+${ginkgo_args[@]}}" "${e2e_test}" -- "${auth_config[@]:+${auth_config[@]}}" --ginkgo.flakeAttempts="${FLAKE_ATTEMPTS}" --host="${KUBE_MASTER_URL}" --provider="${KUBERNETES_PROVIDER}" --gce-project="${PROJECT:-}" --gce-zone="${ZONE:-}" --gke-cluster="${CLUSTER_NAME:-}" --kube-master="${KUBE_MASTER:-}" --cluster-tag="${CLUSTER_ID:-}" --repo-root="${KUBE_ROOT}" --node-instance-group="${NODE_INSTANCE_GROUP:-}" --prefix="${KUBE_GCE_INSTANCE_PREFIX:-e2e}" --network="${KUBE_GCE_NETWORK:-${KUBE_GKE_NETWORK:-e2e}}" --federated-kube-context="${FEDERATION_KUBE_CONTEXT:-e2e-federation}" ${KUBE_CONTAINER_RUNTIME:+"--container-runtime=${KUBE_CONTAINER_RUNTIME}"} ${MASTER_OS_DISTRIBUTION:+"--master-os-distro=${MASTER_OS_DISTRIBUTION}"} ${NODE_OS_DISTRIBUTION:+"--node-os-distro=${NODE_OS_DISTRIBUTION}"} ${NUM_NODES:+"--num-nodes=${NUM_NODES}"} ${E2E_CLEAN_START:+"--clean-start=true"} ${E2E_MIN_STARTUP_PODS:+"--minStartupPods=${E2E_MIN_STARTUP_PODS}"} ${E2E_REPORT_DIR:+"--report-dir=${E2E_REPORT_DIR}"} ${E2E_REPORT_PREFIX:+"--report-prefix=${E2E_REPORT_PREFIX}"} "${@:-}"' exited with status 1
Call stack:
  1: ./hack/ginkgo-e2e.sh:117 main(...)
Exiting with status 1
2017/02/20 15:17:59 util.go:98: Step './hack/ginkgo-e2e.sh --ginkgo.focus=\[Conformance\]' finished in 357.502731ms
2017/02/20 15:17:59 e2e.go:126: Something went wrong: encountered 1 errors: [exit status 1]
```

**Comment by Pensu** [comment]
I am also hitting the above error. @mikkeloscar

**Comment by rtuin** [comment]
I think this workaround commit should be merged into this repo!

**Comment by mwitkow** [comment]
Please do, just hit this myself :)

**Comment by favadi** [comment]
@egbertp do you mind creating a PR?

**Comment by nphase** [comment]
Please do!

**Comment by AlmogBaku** [comment]
@elazarl ?

**Comment by erikdubbelboer** [comment]
@elazarl any idea when this will be fixed?

**Comment by elazarl** [comment]
I'll try to fix it today. It's not a hard issue, but somehow I didn't
manage to find the time yet.

**Comment by elazarl** [comment]
Can someone please test this issue, and verify the new certificate is indeed good?

**Comment by ijin82** [comment]
@elazarl thank you for your job! Works for me. 
But, looks like that app write INFO messages to **stderr**, not to **stdout**. 
Also i have to read the doc about howto switch off info log at all.

**Comment by elazarl** [comment]
Thanks Ilya, it'll be great if more people would check out the certificate,
to be sure more OS accepts it as another root certificate.

**Comment by ijin82** [comment]
@elazarl i've tested on Ubuntu 16.04.2 LTS x64
