### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by g0ku704** [elazarl/goproxy#502]
Similar to [this](https://github.com/elazarl/goproxy/issues/461)

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x6b3260]

goroutine 1287 [running]:
github.com/elazarl/goproxy.(*ProxyHttpServer).handleHttps.func2()
        /go/pkg/mod/github.com/elazarl/goproxy@v0.0.0-20221015165544-a0805db90819/https.go:249 +0xd60
created by github.com/elazarl/goproxy.(*ProxyHttpServer).handleHttps
        /go/pkg/mod/github.com/elazarl/goproxy@v0.0.0-20221015165544-a0805db90819/https.go:211 +0x611
```

https://github.com/elazarl/goproxy/blob/master/https.go#L249

**Comment by kostyay** [comment]
Whats the status of this PR? Any plans to merge it?

**Comment by danmanor** [comment]
Is this issue resolved ?

**Comment by g0ku704** [comment]
> Is this issue resolved ?

Yes, I've added a nil check that was causing the crash and merged with the main branch now. But the release package is not updated yet. (https://github.com/elazarl/goproxy/pull/507)
